### PR TITLE
Added weekday display in header over the collection view.

### PR DESCRIPTION
**Pull request by Hout**
As requested in issue #4.

### CODE REVIEW

**Comment by wlisac** [comment]
@Hout Thanks for the great calendar control. Are there plans to merge in this PR?

**Comment by wlisac** [comment]
@jmig Thanks for this great calendar control. Are there plans to merge in this PR?

**Comment by ybbaigo** [comment]
@jmig Any updates about this thread? any plans to merge this PR?

**Comment by jmig** [comment]
Feature added with https://github.com/jivesoftware/PDTSimpleCalendar/pull/67

@Hout I wanted to thank you again for your work on this feature, I know your work has been an inspiration for @ybbaigo. I apologize for the stalling PR.

**Pull request closed without merging**
